# Generated by Django 3.1.6 on 2021-06-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='https://i.ibb.co/XkLDDnV/placeholder-image-768x576.png', max_length=200, null=True),
        ),
    ]
