export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_SHIPPING_METHOD = "SAVE_SHIPPING_METHOD";

export const CLEAR_CART_ITEMS = "CLEAR_CART_ITEMS";
